/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package healthcare;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class adminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form adminDashboard
     */
    public adminDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        docTablee = new javax.swing.JButton();
        adddoctorr = new javax.swing.JButton();
        patientTablee = new javax.swing.JButton();
        LOgoutt = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Maiandra GD", 1, 39)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Medico Health Care Management System");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Maiandra GD", 1, 29)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Admin Dashboard");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        docTablee.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        docTablee.setText("All Doctors");
        docTablee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docTableeActionPerformed(evt);
            }
        });
        jPanel1.add(docTablee, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 47, 228, -1));

        adddoctorr.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        adddoctorr.setText("Add New Doctor");
        adddoctorr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adddoctorrActionPerformed(evt);
            }
        });
        jPanel1.add(adddoctorr, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 97, 228, -1));

        patientTablee.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        patientTablee.setText("All Patients");
        patientTablee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientTableeActionPerformed(evt);
            }
        });
        jPanel1.add(patientTablee, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 147, 228, -1));

        LOgoutt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LOgoutt.setText("Logout");
        LOgoutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOgouttActionPerformed(evt);
            }
        });
        jPanel1.add(LOgoutt, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 342, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Add New Admin");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 220, 30));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("All Appointment");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 220, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 340, 430));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image1/admin.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adddoctorrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adddoctorrActionPerformed
new doctorlogin().setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_adddoctorrActionPerformed

    private void docTableeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docTableeActionPerformed
new allDoctor().setVisible(true);
dispose();        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_docTableeActionPerformed

    private void patientTableeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientTableeActionPerformed
new allPatient().setVisible(true);
dispose();        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_patientTableeActionPerformed

    private void LOgouttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOgouttActionPerformed
JOptionPane.showMessageDialog(null, "LOgout successfully!"); 
new homepage().setVisible(true);
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_LOgouttActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new editAppointment().setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       new addAdmin().setVisible(true);
        dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LOgoutt;
    private javax.swing.JButton adddoctorr;
    private javax.swing.JButton docTablee;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton patientTablee;
    // End of variables declaration//GEN-END:variables
}
