/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package healthcare;
import java.sql.*;
import javax.swing.JOptionPane;


public class homepage extends javax.swing.JFrame {
Connection con=null;

    /**
     * Creates new form homepage
     */
    public homepage() {
        initComponents();
        con=connectionclass.connectDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        patientuser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        patientpass = new javax.swing.JPasswordField();
        loginPatient = new javax.swing.JButton();
        singup = new javax.swing.JButton();
        clearpatient = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        docuser = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        docpass = new javax.swing.JPasswordField();
        loginDoc = new javax.swing.JButton();
        cleardoc = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        adminuser = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        adminpass = new javax.swing.JPasswordField();
        loginAdmin = new javax.swing.JButton();
        clearadmin = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 3, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("\"your health is our top priority\"");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 460, 40));

        jLabel1.setBackground(new java.awt.Color(204, 255, 255));
        jLabel1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Medico Health Care Centre");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 1, 2, 1, new java.awt.Color(153, 204, 255)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 1080, 60));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 3, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel6.setText("Go To Patient Dashboard");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("User name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        patientuser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        patientuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientuserActionPerformed(evt);
            }
        });
        jPanel1.add(patientuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 150, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        patientpass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        patientpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientpassActionPerformed(evt);
            }
        });
        jPanel1.add(patientpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 150, -1));

        loginPatient.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loginPatient.setText("Login ");
        loginPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginPatientActionPerformed(evt);
            }
        });
        jPanel1.add(loginPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, 24));

        singup.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        singup.setText("Make new Account Here");
        singup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singupActionPerformed(evt);
            }
        });
        jPanel1.add(singup, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, 25));

        clearpatient.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clearpatient.setText("Clear");
        clearpatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearpatientActionPerformed(evt);
            }
        });
        jPanel1.add(clearpatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 263, -1, 20));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image1/OIP (1).jpg"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 290, 330));

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 3, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel7.setText("Go to Doctor's Dashboard");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 156, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("User name");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 201, -1, -1));

        docuser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel3.add(docuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 202, 151, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Password");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 234, -1, -1));

        docpass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel3.add(docpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 235, 151, -1));

        loginDoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loginDoc.setText("Login");
        loginDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginDocActionPerformed(evt);
            }
        });
        jPanel3.add(loginDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, -1));

        cleardoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cleardoc.setText("Clear");
        cleardoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleardocActionPerformed(evt);
            }
        });
        jPanel3.add(cleardoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image1/R.jpg"))); // NOI18N
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 250, 280, 320));

        jPanel2.setBackground(new java.awt.Color(182, 215, 248));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 3, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setText("Go to Admin Panel");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("User name");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        adminuser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        adminuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminuserActionPerformed(evt);
            }
        });
        jPanel2.add(adminuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 150, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Password");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        adminpass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        adminpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminpassActionPerformed(evt);
            }
        });
        jPanel2.add(adminpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 150, -1));

        loginAdmin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loginAdmin.setText("Login");
        loginAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginAdminActionPerformed(evt);
            }
        });
        jPanel2.add(loginAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 70, -1));

        clearadmin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clearadmin.setText("Clear");
        clearadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearadminActionPerformed(evt);
            }
        });
        jPanel2.add(clearadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 70, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image1/R (1).jpg"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 70, 80));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 290, 330));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image1/homepage.jpg"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void singupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singupActionPerformed
new patientregestration().setVisible(true);
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_singupActionPerformed

    private void patientpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientpassActionPerformed

    private void adminuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminuserActionPerformed

    private void adminpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminpassActionPerformed

    private void loginAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginAdminActionPerformed
String ss = adminuser.getText();
        String pp = adminpass.getText();
        try {
            String Sql = "Select Username,password From admin";
            Statement st = con.createStatement();
            ResultSet rt = st.executeQuery(Sql);
            int count = 0;
            while (rt.next()) {
                String name = rt.getString("Username");
                String pas = rt.getString("password");
                if (name.equals(ss) && pas.equals(pp)) {
                    JOptionPane.showMessageDialog(null, "Loging In....");
                    new adminDashboard().setVisible(true);
                    dispose();
                    count = 1;
                }
            }
            if (count == 0) {
                
                adminuser.getText();adminuser.setText("");
                adminpass.getText();adminpass.setText("");


                JOptionPane.showMessageDialog(null, "Wrong Password");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_loginAdminActionPerformed

    private void loginPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginPatientActionPerformed
String ss = patientuser.getText();
        String pp = patientpass.getText();
        try {
            String Sql = "Select userName,password From patient";
            Statement st = con.createStatement();
            ResultSet rt = st.executeQuery(Sql);
            int count = 0;
            while (rt.next()) {
                String name = rt.getString("userName");
                String pas = rt.getString("password");
                if (name.equals(ss ) && pas.equals(pp))
                {
                    JOptionPane.showMessageDialog(null, "Loging In....");
                    new patientDashboard().setVisible(true);
                    dispose();
                    count = 1;
                }
            }
            if (count == 0) {
                patientuser.getText();patientuser.setText("");
patientpass.getText();patientpass.setText("");
                JOptionPane.showMessageDialog(null, "Wrong Password");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
// TODO add your handling code here:
        /*String ss = patientuser.getText();
        String pp = patientpass.getText();
        try {
            String Sql = "Select userName,password From patient";
            Statement st = con.createStatement();
            ResultSet rt = st.executeQuery(Sql);
            int count = 0;
            while (rt.next()) {
                String name = rt.getString("userName");
                String pas = rt.getString("password");
                if (name.equals(ss) && pas.equals(pp)) {
                    new patientDashboard().setVisible(true);
                    dispose();
                    count = 1;
                }
            }
            if (count == 0) {
                JOptionPane.showMessageDialog(null, "Wrong Password");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:*/
    }//GEN-LAST:event_loginPatientActionPerformed

    private void loginDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginDocActionPerformed
String ss = docuser.getText();
        String pp = docpass.getText();
        try {
            String Sql = "Select docUsername,docPassword From doctor";
            Statement st = con.createStatement();
            ResultSet rt = st.executeQuery(Sql);
            int count = 0;
            while (rt.next()) {
                String name = rt.getString("docUsername");
                String pas = rt.getString("docPassword");
                if (name.equals(ss) && pas.equals(pp)) {
                    JOptionPane.showMessageDialog(null, "Loging In....");
                    new doctorDashboard().setVisible(true);
                    dispose();
                    count = 1;
                }
            }
            if (count == 0) {
                JOptionPane.showMessageDialog(null, "Wrong Password");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_loginDocActionPerformed

    private void patientuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientuserActionPerformed

    private void clearadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearadminActionPerformed
adminuser.getText();adminuser.setText("");
adminpass.getText();adminpass.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_clearadminActionPerformed

    
    private void clearpatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearpatientActionPerformed
patientuser.getText();patientuser.setText("");
patientpass.getText();patientpass.setText("");// TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_clearpatientActionPerformed

    private void cleardocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleardocActionPerformed
docuser.getText();docuser.setText("");
docpass.getText();docpass.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_cleardocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField adminpass;
    private javax.swing.JTextField adminuser;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton clearadmin;
    private javax.swing.JButton cleardoc;
    private javax.swing.JButton clearpatient;
    private javax.swing.JPasswordField docpass;
    private javax.swing.JTextField docuser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton loginAdmin;
    private javax.swing.JButton loginDoc;
    private javax.swing.JButton loginPatient;
    private javax.swing.JPasswordField patientpass;
    private javax.swing.JTextField patientuser;
    private javax.swing.JButton singup;
    // End of variables declaration//GEN-END:variables
}
